version: "3.7"
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
  ms-produto:
    image: ms-produto
    container_name: ms-produto
    ports:
      - 8081:8081
    restart: unless-stopped
    environment:
      AMQP_HOST: rabbit
  rabbit:
    image: rabbitmq:3-management-alpine
    container_name: rabbit
    ports:
      - 15672:15672
      - 5672:5672
    restart: unless-stopped
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
  jaeger:
    image: "jaegertracing/all-in-one:1.23"
    ports:
      - 6831:6831
    environment:
      JAEGER_UDP_HOST: jaeger
      JAEGER_UDP_PORT: 6831
volumes:
  prom_data:
